language: python

python:
  - "3.5"
  - "2.7"

install:
  - make install

jobs:
  include:
    - stage: "Tests"                # naming the Tests stage
      script: make test
    - stage: "Linter"                # naming the Tests stage
      script: make lint