language: python

python:
  - "3.5"
  - "2.7"

install:
  - make install

script:
  - make lint
  - make test

jobs:
  include:
    - stage: "Tests"                # naming the Tests stage
      name: "Unit Tests"            # names the first Tests stage job
      script: make test
    - script: make lint
      name: "Linter"     # names the second Tests stage job